language: rust
dist: trusty
cache: cargo
sudo: required
addons:
    apt:
        packages:
            - libssl-dev
rust:
- stable
- nightly-2018-05-03
- nightly-2018-05-02
- nightly-2018-05-01
- nightly-2018-04-25
- nightly-2018-04-20
- nightly-2018-04-16

matrix:
  allow_failures:
  - rust: nightly
script:
- cargo clean
- cargo build
- cargo test

